<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZlhyrn4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZlhyrn4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZlhyrn4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZlhyrn4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZlhyrn4\appDevDebugProjectContainer([
    'container.build_hash' => 'Zlhyrn4',
    'container.build_id' => '64f79371',
    'container.build_time' => 1642501663,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZlhyrn4');
