<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGexvkok\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGexvkok/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGexvkok.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGexvkok\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGexvkok\appDevDebugProjectContainer([
    'container.build_hash' => 'Gexvkok',
    'container.build_id' => '3e23e069',
    'container.build_time' => 1643817947,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGexvkok');
