<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN6dce5e\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN6dce5e/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerN6dce5e.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerN6dce5e\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerN6dce5e\appDevDebugProjectContainer([
    'container.build_hash' => 'N6dce5e',
    'container.build_id' => '4dc2985e',
    'container.build_time' => 1643817982,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN6dce5e');
