<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRtubiup\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRtubiup/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRtubiup.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRtubiup\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRtubiup\appDevDebugProjectContainer([
    'container.build_hash' => 'Rtubiup',
    'container.build_id' => '0b262162',
    'container.build_time' => 1639735821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRtubiup');
